#!/usr/bin/env python3
"""make_map.py - deterministic occupancy grid for sim/worlds/warehouse.sdf.

Design choice (documented per brief m3-02): instead of SLAM-mapping the
world (non-deterministic, slow at the container's ~0.1 real-time factor),
this script writes the map directly from the known, static world geometry.
Every rectangle below is copied from the model poses/sizes in
sim/worlds/warehouse.sdf. If the world changes, re-run this script; the
two files can be diffed against the SDF by inspection.

Output: sim/scenarios/maps/map.pgm + map.yaml (trinary, 0.05 m/px).
Occupied = 0 (black), free = 254 (white). No external dependencies.

The DoorGap lintel (z = 2.35 m) is intentionally NOT in the map: it is
overhead geometry the lidar (z ~ 0.30 m) never sees and the vehicle
drives under. The two door posts ARE in the map.

Usage: python3 make_map.py [output_dir]   (default: ../maps next to this file)
"""

import os
import struct
import sys

RESOLUTION = 0.05          # m / pixel
ORIGIN_X, ORIGIN_Y = -15.5, -10.5   # world coords of the lower-left pixel
WIDTH_M, HEIGHT_M = 31.0, 21.0      # covers walls at |x|<=15.2, |y|<=10.2

FREE, OCCUPIED = 254, 0

# Axis-aligned obstacle rectangles: (center_x, center_y, size_x, size_y).
# Source: sim/worlds/warehouse.sdf model poses and box sizes.
RECTS = [
    # Perimeter walls
    (0.0,   10.1, 30.6, 0.2),     # WallNorth
    (-5.65, -10.1, 19.3, 0.2),    # WallSouthWest
    (11.65, -10.1, 7.3, 0.2),     # WallSouthEast
    (15.1,  0.0,  0.2, 20.0),     # WallEast
    (-15.1, 0.0,  0.2, 20.0),     # WallWest
    # DoorGap posts (model pose 6,-10.1; link offsets +-2.1, size 0.2x0.3)
    (3.9,  -10.1, 0.2, 0.3),      # post_west
    (8.1,  -10.1, 0.2, 0.3),      # post_east
    # Rack rows (4.0 x 1.2 each)
    (-6.0, 4.0, 4.0, 1.2),        # RackA1
    (0.0,  4.0, 4.0, 1.2),        # RackA2
    (6.0,  4.0, 4.0, 1.2),        # RackA3
    (-6.0, -1.0, 4.0, 1.2),       # RackB1
    (0.0,  -1.0, 4.0, 1.2),       # RackB2
    (6.0,  -1.0, 4.0, 1.2),       # RackB3
    # Fixed stations
    (13.4, 5.0, 3.0, 1.0),        # ConveyorStation
    (-14.5, -6.0, 0.8, 0.8),      # ChargerStation
]


def main() -> None:
    out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.normpath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'maps'))
    os.makedirs(out_dir, exist_ok=True)

    w_px = round(WIDTH_M / RESOLUTION)
    h_px = round(HEIGHT_M / RESOLUTION)
    grid = bytearray([FREE]) * (w_px * h_px)

    def fill(cx, cy, sx, sy):
        x0, x1 = cx - sx / 2.0, cx + sx / 2.0
        y0, y1 = cy - sy / 2.0, cy + sy / 2.0
        j0 = max(0, int((x0 - ORIGIN_X) / RESOLUTION))
        j1 = min(w_px - 1, int((x1 - ORIGIN_X) / RESOLUTION))
        i0 = max(0, int((y0 - ORIGIN_Y) / RESOLUTION))
        i1 = min(h_px - 1, int((y1 - ORIGIN_Y) / RESOLUTION))
        for i in range(i0, i1 + 1):          # i: row counted from BOTTOM
            row = (h_px - 1 - i) * w_px       # PGM stores top row first
            for j in range(j0, j1 + 1):
                grid[row + j] = OCCUPIED

    for rect in RECTS:
        fill(*rect)

    pgm_path = os.path.join(out_dir, 'map.pgm')
    with open(pgm_path, 'wb') as f:
        f.write(b'P5\n# generated by sim/scenarios/tools/make_map.py '
                b'from sim/worlds/warehouse.sdf\n')
        f.write(f'{w_px} {h_px}\n255\n'.encode())
        f.write(bytes(grid))

    yaml_path = os.path.join(out_dir, 'map.yaml')
    with open(yaml_path, 'w') as f:
        f.write(
            'image: map.pgm\n'
            'mode: trinary\n'
            f'resolution: {RESOLUTION}\n'
            f'origin: [{ORIGIN_X}, {ORIGIN_Y}, 0.0]\n'
            'negate: 0\n'
            'occupied_thresh: 0.65\n'
            'free_thresh: 0.25\n')

    occ = sum(1 for v in grid if v == OCCUPIED)
    print(f'wrote {pgm_path} ({w_px}x{h_px} px, {occ} occupied cells) '
          f'and {yaml_path}')


if __name__ == '__main__':
    main()
